const express = require('express');
const router = express.Router();
const expenseController = require('../controllers/expense.controller');
const authMiddleware = require('../middleware/auth.middleware');
router.use(authMiddleware);
router.post('/', expenseController.create);
router.get('/', expenseController.getAll);
router.get('/stats', expenseController.getStats);
router.get('/anomalies', expenseController.getAnomalies);
router.get('/export', expenseController.exportCsv);
router.post('/import', expenseController.importCsv);
router.get('/recurring', expenseController.getRecurring);
router.post('/recurring', expenseController.createRecurring);
router.put('/recurring/:id', expenseController.updateRecurring);
router.delete('/recurring/:id', expenseController.deleteRecurring);
router.post('/recurring/process', expenseController.processRecurringNow);
router.get('/:id', expenseController.getOne);
router.put('/:id', expenseController.update);
router.delete('/:id', expenseController.delete);

module.exports = router;